//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbs_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int FlightNo { get; set; }
        public int CustomerID { get; set; }
        public int Seats { get; set; }
        public double BookingAmount { get; set; }
        public System.DateTime Arrival { get; set; }
        public System.DateTime Departure { get; set; }
        public Nullable<bool> CheckedIn { get; set; }
        public Nullable<bool> Cancelled { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
